on:
    push:
      tags:
        - 'v*'
    release:
        types: [published]
  
name: Create Release
  
jobs:
    once:
      name: Create single release for all builds
      runs-on: ubuntu-latest
      outputs:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
      steps:
        - name: Create a release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: Release ${{ github.ref }}
            draft: false
            prerelease: false
  
    build:
      name: Create Release
      needs: once
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          os: [macOS-latest, ubuntu-latest, windows-latest]
  
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21'
        - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
          name: Build Linux and MacOS
          run: CGO_ENABLED=0 go build -v -o helloworld
        - if: matrix.os == 'windows-latest'
          name: Build Windows
          run: cmd /C "set CGO_ENABLED=0 && go build -v -o helloworld"
        - name: Test
          run: go test -v ./...
        - if: matrix.os == 'windows-latest'
          name: create zip
          uses: vimtor/action-zip@v1.1
          with:
            files: helloworld
            dest: helloworld-${{ matrix.os }}-amd64-${{ github.ref_name }}.zip
        - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
          name: create-archive
          run: tar -czf helloworld-${{ matrix.os }}-amd64-${{ github.ref_name }}.tar.gz helloworld
      
        - if: matrix.os == 'ubuntu-latest' || matrix.os == 'macOS-latest'
          name: Upload Release Asset Linux MacOS
          id: upload-release-asset-linux-macos
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.once.outputs.upload_url }}
            asset_path: ./helloworld-${{ matrix.os }}-amd64-${{ github.ref_name }}.tar.gz
            asset_name: helloworld-${{ matrix.os }}-amd64-${{ github.ref_name }}.tar.gz
            asset_content_type: application/x-tgz
        - if: matrix.os == 'windows-latest'
          name: Upload Release Asset Windows
          id: upload-release-asset-windows
          uses: actions/upload-release-asset@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            upload_url: ${{ needs.once.outputs.upload_url }}
            asset_path: ./helloworld-${{ matrix.os }}-amd64-${{ github.ref_name }}.zip
            asset_name: helloworld-${{ matrix.os }}-amd64-${{ github.ref_name }}.zip
            asset_content_type: application/zip